services:
  - type: web
    name: free-calculator-mcp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:mcp.app --host 0.0.0.0 --port 8000
    plan: free
